import React, { useState, useRef } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Save, DollarSign, Calendar, Target, FileText, Upload, X } from 'lucide-react';
import AdminNav from '../../components/admin/AdminNav';
import { useIsMobile, useIsTablet } from '../../hooks/useMediaQuery';

// Mock data for dropdowns
const STRATEGIES = ['Growth', 'Income', 'Balanced', 'Opportunistic', 'Distressed Assets'];
const STATUSES = ['Launching Soon', 'Open', 'Closed', 'Liquidating'];

export default function CreateFund() {
    const isMobile = useIsMobile();
    const isTablet = useIsTablet();
    const navigate = useNavigate();

    // Form State
    const [formData, setFormData] = useState({
        name: '',
        id: 'PCIG-FUND-' + Math.floor(100 + Math.random() * 900), // Auto-generate ID suggestion
        strategy: 'Growth',
        status: 'Launching Soon',
        targetIRR: '',
        hardCap: '',
        minInvestment: '',
        lockUp: '',
        description: '',
        managementFee: '2.0%',
        performanceFee: '20%'
    });

    const [files, setFiles] = useState<{
        prospectus: File | null;
        termSheet: File | null;
        image: File | null;
    }>({
        prospectus: null,
        termSheet: null,
        image: null
    });

    const prospectusInputRef = useRef<HTMLInputElement>(null);
    const termSheetInputRef = useRef<HTMLInputElement>(null);
    const imageInputRef = useRef<HTMLInputElement>(null);

    const [isSubmitting, setIsSubmitting] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const handleChange = (field: string, value: string) => {
        setFormData(prev => ({ ...prev, [field]: value }));
    };

    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>, type: 'prospectus' | 'termSheet' | 'image') => {
        if (e.target.files && e.target.files[0]) {
            setFiles(prev => ({ ...prev, [type]: e.target.files![0] }));
        }
    };

    const removeFile = (type: 'prospectus' | 'termSheet' | 'image') => {
        setFiles(prev => ({ ...prev, [type]: null }));
        if (type === 'prospectus' && prospectusInputRef.current) prospectusInputRef.current.value = '';
        if (type === 'termSheet' && termSheetInputRef.current) termSheetInputRef.current.value = '';
        if (type === 'image' && imageInputRef.current) imageInputRef.current.value = '';
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setIsSubmitting(true);
        setError(null);

        try {
            const data = new FormData();
            
            // Append regular fields
            data.append('name', formData.name);
            data.append('fund_code', formData.id);
            data.append('strategy', formData.strategy);
            
            // Map status to backend expected values if needed
            const statusMap: {[key: string]: string} = {
                'Launching Soon': 'coming_soon',
                'Open': 'open',
                'Closed': 'closed',
                'Liquidating': 'liquidating'
            };
            data.append('status', statusMap[formData.status] || formData.status.toLowerCase());
            
            data.append('target_irr', formData.targetIRR);
            data.append('cap', formData.hardCap.replace(/[^0-9.]/g, ''));
            data.append('min_investment', formData.minInvestment.replace(/[^0-9.]/g, ''));
            data.append('lock_up_period', formData.lockUp);
            data.append('description', formData.description);
            data.append('management_fee', formData.managementFee.replace(/[^0-9.]/g, ''));
            data.append('performance_fee', formData.performanceFee.replace(/[^0-9.]/g, ''));
            
            // Append files
            if (files.prospectus) {
                data.append('prospectus', files.prospectus);
            }
            if (files.termSheet) {
                data.append('term_sheet', files.termSheet);
            }
            if (files.image) {
                data.append('image', files.image);
            }

            // Slug is generated by backend to ensure uniqueness
            // data.append('slug', slug);

            // Get token manually to ensure it's fresh and present
            const token = localStorage.getItem('token');
            if (!token) {
                // If no token, show error and do NOT redirect automatically
                setError('Authentication session missing. Please log in again in a new tab.');
                setIsSubmitting(false);
                return;
            }

            try {
                // Use direct axios call to bypass global interceptors that might cause premature redirects
                // and to ensure we have full control over headers and credentials
                await axios.post('http://127.0.0.1:8000/api/admin/funds', data, {
                    headers: {
                        'Authorization': `Bearer ${token}`,
                        'Accept': 'application/json'
                        // Content-Type is automatically set by browser for FormData
                    },
                    maxBodyLength: Infinity,
                    maxContentLength: Infinity,
                    withCredentials: false // Critical: Prevent sending cookies/CSRF token which causes 401/419
                });

                navigate('/admin/funds');
            } catch (innerErr: any) {
                console.error('Inner axios error:', innerErr);
                // Throw to outer catch to handle consistency
                throw innerErr;
            }
        } catch (err: any) {
            console.error('Error creating fund:', err);
            
            // Prevent any redirect by stopping propagation if possible (though catch already does this for the promise chain)
            
            if (err.response) {
                if (err.response.status === 401) {
                    setError('Session expired or unauthorized. Please refresh the page or log in again.');
                } else if (err.response.data && err.response.data.message) {
                    setError(err.response.data.message);
                } else {
                    setError(`Server error: ${err.response.status} - ${err.response.data?.message || 'Unknown error'}`);
                }
            } else if (err.request) {
                setError('No response from server. Please check your connection.');
            } else {
                setError(`Failed to create fund: ${err.message}`);
            }
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
        <div style={{ fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif", backgroundColor: '#F8FAFC', minHeight: '100vh', width: '100%', margin: 0, padding: 0 }}>
            <AdminNav />

            <div style={{
                maxWidth: '1000px',
                margin: '0 auto',
                padding: isMobile ? '16px 16px 32px' : isTablet ? '24px 32px' : '32px 40px',
                boxSizing: 'border-box'
            }}>
                {/* Header */}
                <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 24 }}>
                    <button
                        onClick={() => navigate(-1)}
                        style={{
                            background: 'none', border: 'none', cursor: 'pointer', padding: 8, marginLeft: -8,
                            color: '#64748B', display: 'flex', alignItems: 'center', justifyContent: 'center'
                        }}
                    >
                        <ArrowLeft size={20} />
                    </button>
                    <div>
                        <h1 style={{ fontSize: `clamp(20px, 2.5vw, 24px)`, fontWeight: 700, color: '#0F172A', margin: 0 }}>Create New Fund</h1>
                        <p style={{ fontSize: `clamp(13px, 1.5vw, 14px)`, color: '#64748B', margin: '4px 0 0 0' }}>Set up a new investment vehicle for investors.</p>
                    </div>
                </div>

                <form onSubmit={handleSubmit} style={{ display: 'grid', gap: 24 }}>

                    {/* Section 1: General Info */}
                    <div style={{ backgroundColor: '#FFFFFF', borderRadius: 12, border: '1px solid #E2E8F0', padding: isMobile ? 16 : 24 }}>
                        <h2 style={{ fontSize: 16, fontWeight: 600, color: '#0F172A', marginTop: 0, marginBottom: 20, display: 'flex', alignItems: 'center', gap: 8 }}>
                            <div style={{ width: 4, height: 16, backgroundColor: '#1E3A5F', borderRadius: 2 }}></div>
                            General Information
                        </h2>
                        <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr', gap: 20 }}>
                            <div>
                                <label style={{ display: 'block', fontSize: 13, fontWeight: 500, color: '#334155', marginBottom: 6 }}>Fund Name</label>
                                <input
                                    type="text"
                                    value={formData.name}
                                    onChange={(e) => handleChange('name', e.target.value)}
                                    placeholder="e.g. PCIG Income Fund II"
                                    required
                                    style={{ width: '100%', padding: '10px 12px', borderRadius: 6, border: '1px solid #CBD5E1', fontSize: 14, outline: 'none', boxSizing: 'border-box' }}
                                />
                            </div>
                            <div>
                                <label style={{ display: 'block', fontSize: 13, fontWeight: 500, color: '#334155', marginBottom: 6 }}>Fund ID</label>
                                <input
                                    type="text"
                                    value={formData.id}
                                    onChange={(e) => handleChange('id', e.target.value)}
                                    placeholder="e.g. PCIG-FUND-00X"
                                    required
                                    style={{ width: '100%', padding: '10px 12px', borderRadius: 6, border: '1px solid #CBD5E1', fontSize: 14, outline: 'none', boxSizing: 'border-box', fontFamily: 'monospace' }}
                                />
                            </div>
                            <div>
                                <label style={{ display: 'block', fontSize: 13, fontWeight: 500, color: '#334155', marginBottom: 6 }}>Strategy</label>
                                <select
                                    value={formData.strategy}
                                    onChange={(e) => handleChange('strategy', e.target.value)}
                                    style={{ width: '100%', padding: '10px 12px', borderRadius: 6, border: '1px solid #CBD5E1', fontSize: 14, outline: 'none', boxSizing: 'border-box', backgroundColor: '#fff' }}
                                >
                                    {STRATEGIES.map(s => <option key={s} value={s}>{s}</option>)}
                                </select>
                            </div>
                            <div>
                                <label style={{ display: 'block', fontSize: 13, fontWeight: 500, color: '#334155', marginBottom: 6 }}>Initial Status</label>
                                <select
                                    value={formData.status}
                                    onChange={(e) => handleChange('status', e.target.value)}
                                    style={{ width: '100%', padding: '10px 12px', borderRadius: 6, border: '1px solid #CBD5E1', fontSize: 14, outline: 'none', boxSizing: 'border-box', backgroundColor: '#fff' }}
                                >
                                    {STATUSES.map(s => <option key={s} value={s}>{s}</option>)}
                                </select>
                            </div>
                        </div>
                    </div>

                    {/* Section 2: Investment Parameters */}
                    <div style={{ backgroundColor: '#FFFFFF', borderRadius: 12, border: '1px solid #E2E8F0', padding: isMobile ? 16 : 24 }}>
                        <h2 style={{ fontSize: 16, fontWeight: 600, color: '#0F172A', marginTop: 0, marginBottom: 20, display: 'flex', alignItems: 'center', gap: 8 }}>
                            <div style={{ width: 4, height: 16, backgroundColor: '#1E3A5F', borderRadius: 2 }}></div>
                            Investment Parameters
                        </h2>
                        <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : isTablet ? '1fr 1fr' : 'repeat(3, 1fr)', gap: 20 }}>
                            <div>
                                <label style={{ fontSize: 13, fontWeight: 500, color: '#334155', marginBottom: 6, display: 'flex', alignItems: 'center', gap: 6 }}>
                                    <Target size={14} /> Target IRR
                                </label>
                                <input
                                    type="text"
                                    value={formData.targetIRR}
                                    onChange={(e) => handleChange('targetIRR', e.target.value)}
                                    placeholder="e.g. 12-15%"
                                    style={{ width: '100%', padding: '10px 12px', borderRadius: 6, border: '1px solid #CBD5E1', fontSize: 14, outline: 'none', boxSizing: 'border-box' }}
                                />
                            </div>
                            <div>
                                <label style={{ fontSize: 13, fontWeight: 500, color: '#334155', marginBottom: 6, display: 'flex', alignItems: 'center', gap: 6 }}>
                                    <DollarSign size={14} /> Hard Cap
                                </label>
                                <input
                                    type="text"
                                    value={formData.hardCap}
                                    onChange={(e) => handleChange('hardCap', e.target.value)}
                                    placeholder="e.g. $50M"
                                    style={{ width: '100%', padding: '10px 12px', borderRadius: 6, border: '1px solid #CBD5E1', fontSize: 14, outline: 'none', boxSizing: 'border-box' }}
                                />
                            </div>
                            <div>
                                <label style={{ fontSize: 13, fontWeight: 500, color: '#334155', marginBottom: 6, display: 'flex', alignItems: 'center', gap: 6 }}>
                                    <DollarSign size={14} /> Min Investment
                                </label>
                                <input
                                    type="text"
                                    value={formData.minInvestment}
                                    onChange={(e) => handleChange('minInvestment', e.target.value)}
                                    placeholder="e.g. $25,000"
                                    style={{ width: '100%', padding: '10px 12px', borderRadius: 6, border: '1px solid #CBD5E1', fontSize: 14, outline: 'none', boxSizing: 'border-box' }}
                                />
                            </div>
                            <div>
                                <label style={{ fontSize: 13, fontWeight: 500, color: '#334155', marginBottom: 6, display: 'flex', alignItems: 'center', gap: 6 }}>
                                    <Calendar size={14} /> Lock-up Period
                                </label>
                                <input
                                    type="text"
                                    value={formData.lockUp}
                                    onChange={(e) => handleChange('lockUp', e.target.value)}
                                    placeholder="e.g. 12 Months"
                                    style={{ width: '100%', padding: '10px 12px', borderRadius: 6, border: '1px solid #CBD5E1', fontSize: 14, outline: 'none', boxSizing: 'border-box' }}
                                />
                            </div>
                            <div>
                                <label style={{ display: 'block', fontSize: 13, fontWeight: 500, color: '#334155', marginBottom: 6 }}>Management Fee</label>
                                <input
                                    type="text"
                                    value={formData.managementFee}
                                    onChange={(e) => handleChange('managementFee', e.target.value)}
                                    style={{ width: '100%', padding: '10px 12px', borderRadius: 6, border: '1px solid #CBD5E1', fontSize: 14, outline: 'none', boxSizing: 'border-box' }}
                                />
                            </div>
                            <div>
                                <label style={{ display: 'block', fontSize: 13, fontWeight: 500, color: '#334155', marginBottom: 6 }}>Performance Fee</label>
                                <input
                                    type="text"
                                    value={formData.performanceFee}
                                    onChange={(e) => handleChange('performanceFee', e.target.value)}
                                    style={{ width: '100%', padding: '10px 12px', borderRadius: 6, border: '1px solid #CBD5E1', fontSize: 14, outline: 'none', boxSizing: 'border-box' }}
                                />
                            </div>
                        </div>
                    </div>

                    {/* Section 3: Description & Documents */}
                    <div style={{ backgroundColor: '#FFFFFF', borderRadius: 12, border: '1px solid #E2E8F0', padding: isMobile ? 16 : 24 }}>
                        <h2 style={{ fontSize: 16, fontWeight: 600, color: '#0F172A', marginTop: 0, marginBottom: 20, display: 'flex', alignItems: 'center', gap: 8 }}>
                            <div style={{ width: 4, height: 16, backgroundColor: '#1E3A5F', borderRadius: 2 }}></div>
                            Fund Details
                        </h2>
                        <div style={{ display: 'grid', gap: 20 }}>
                            <div>
                                <label style={{ display: 'block', fontSize: 13, fontWeight: 500, color: '#334155', marginBottom: 12 }}>Fund Image</label>
                                <div 
                                    onClick={() => !files.image && imageInputRef.current?.click()}
                                    style={{
                                        border: files.image ? '2px solid #10B981' : '2px dashed #E2E8F0', 
                                        borderRadius: 8, padding: 20,
                                        display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 8,
                                        cursor: files.image ? 'default' : 'pointer', 
                                        backgroundColor: files.image ? '#F0FDF4' : '#F8FAFC', 
                                        transition: 'all 0.2s',
                                        position: 'relative',
                                        minHeight: '120px'
                                    }}
                                >
                                    <input 
                                        type="file" 
                                        ref={imageInputRef} 
                                        style={{ display: 'none' }} 
                                        onChange={(e) => handleFileChange(e, 'image')}
                                        accept="image/*"
                                    />
                                    
                                    {files.image ? (
                                        <>
                                            <button 
                                                onClick={(e) => { e.stopPropagation(); removeFile('image'); }}
                                                style={{ position: 'absolute', top: 8, right: 8, background: 'none', border: 'none', cursor: 'pointer', color: '#DC2626' }}
                                            >
                                                <X size={16} />
                                            </button>
                                            <div style={{ width: '100%', height: '100%', maxHeight: '200px', display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden', borderRadius: 4 }}>
                                                <img 
                                                    src={URL.createObjectURL(files.image)} 
                                                    alt="Fund Preview" 
                                                    style={{ maxWidth: '100%', maxHeight: '100%', objectFit: 'contain' }} 
                                                />
                                            </div>
                                            <span style={{ fontSize: 13, fontWeight: 500, color: '#047857', textAlign: 'center', wordBreak: 'break-all' }}>
                                                {files.image.name}
                                            </span>
                                        </>
                                    ) : (
                                        <>
                                            <Upload color="#94A3B8" size={24} />
                                            <span style={{ fontSize: 13, fontWeight: 500, color: '#64748B' }}>Upload Fund Image (JPG, PNG, SVG)</span>
                                            <span style={{ fontSize: 11, color: '#94A3B8' }}>Recommended size: 800x600px</span>
                                        </>
                                    )}
                                </div>
                            </div>

                            <div>
                                <label style={{ display: 'block', fontSize: 13, fontWeight: 500, color: '#334155', marginBottom: 6 }}>Investment Thesis / Description</label>
                                <textarea
                                    value={formData.description}
                                    onChange={(e) => handleChange('description', e.target.value)}
                                    placeholder="Describe the fund's strategy, focus areas, and key selling points for investors..."
                                    rows={5}
                                    style={{ width: '100%', padding: '12px', borderRadius: 6, border: '1px solid #CBD5E1', fontSize: 14, outline: 'none', boxSizing: 'border-box', resize: 'vertical' }}
                                />
                            </div>

                            <div>
                                <label style={{ display: 'block', fontSize: 13, fontWeight: 500, color: '#334155', marginBottom: 12 }}>Offering Documents</label>
                                
                                {error && (
                                    <div style={{ backgroundColor: '#FEF2F2', border: '1px solid #FECACA', borderRadius: 6, padding: '12px', marginBottom: 16, color: '#DC2626', fontSize: 14 }}>
                                        {error}
                                    </div>
                                )}

                                <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr', gap: 16 }}>
                                    {/* Prospectus Upload */}
                                    <div 
                                        onClick={() => !files.prospectus && prospectusInputRef.current?.click()}
                                        style={{
                                            border: files.prospectus ? '2px solid #10B981' : '2px dashed #E2E8F0', 
                                            borderRadius: 8, padding: 20,
                                            display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 8,
                                            cursor: files.prospectus ? 'default' : 'pointer', 
                                            backgroundColor: files.prospectus ? '#F0FDF4' : '#F8FAFC', 
                                            transition: 'all 0.2s',
                                            position: 'relative'
                                        }}
                                    >
                                        <input 
                                            type="file" 
                                            ref={prospectusInputRef} 
                                            style={{ display: 'none' }} 
                                            onChange={(e) => handleFileChange(e, 'prospectus')}
                                            accept=".pdf"
                                        />
                                        
                                        {files.prospectus ? (
                                            <>
                                                <button 
                                                    onClick={(e) => { e.stopPropagation(); removeFile('prospectus'); }}
                                                    style={{ position: 'absolute', top: 8, right: 8, background: 'none', border: 'none', cursor: 'pointer', color: '#DC2626' }}
                                                >
                                                    <X size={16} />
                                                </button>
                                                <FileText color="#10B981" size={24} />
                                                <span style={{ fontSize: 13, fontWeight: 500, color: '#047857', textAlign: 'center', wordBreak: 'break-all' }}>
                                                    {files.prospectus.name}
                                                </span>
                                            </>
                                        ) : (
                                            <>
                                                <Upload color="#94A3B8" size={24} />
                                                <span style={{ fontSize: 13, fontWeight: 500, color: '#64748B' }}>Upload Prospectus (PDF)</span>
                                            </>
                                        )}
                                    </div>

                                    {/* Term Sheet Upload */}
                                    <div 
                                        onClick={() => !files.termSheet && termSheetInputRef.current?.click()}
                                        style={{
                                            border: files.termSheet ? '2px solid #10B981' : '2px dashed #E2E8F0', 
                                            borderRadius: 8, padding: 20,
                                            display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 8,
                                            cursor: files.termSheet ? 'default' : 'pointer', 
                                            backgroundColor: files.termSheet ? '#F0FDF4' : '#F8FAFC', 
                                            transition: 'all 0.2s',
                                            position: 'relative'
                                        }}
                                    >
                                        <input 
                                            type="file" 
                                            ref={termSheetInputRef} 
                                            style={{ display: 'none' }} 
                                            onChange={(e) => handleFileChange(e, 'termSheet')}
                                            accept=".pdf"
                                        />
                                        
                                        {files.termSheet ? (
                                            <>
                                                <button 
                                                    onClick={(e) => { e.stopPropagation(); removeFile('termSheet'); }}
                                                    style={{ position: 'absolute', top: 8, right: 8, background: 'none', border: 'none', cursor: 'pointer', color: '#DC2626' }}
                                                >
                                                    <X size={16} />
                                                </button>
                                                <FileText color="#10B981" size={24} />
                                                <span style={{ fontSize: 13, fontWeight: 500, color: '#047857', textAlign: 'center', wordBreak: 'break-all' }}>
                                                    {files.termSheet.name}
                                                </span>
                                            </>
                                        ) : (
                                            <>
                                                <Upload color="#94A3B8" size={24} />
                                                <span style={{ fontSize: 13, fontWeight: 500, color: '#64748B' }}>Upload Term Sheet (PDF)</span>
                                            </>
                                        )}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Action Bar */}
                    <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 12, marginTop: 8 }}>
                        <button
                            type="button"
                            onClick={() => navigate(-1)}
                            style={{
                                padding: '10px 20px', borderRadius: 8, border: '1px solid #E2E8F0', backgroundColor: '#FFFFFF',
                                color: '#64748B', fontSize: 14, fontWeight: 500, cursor: 'pointer'
                            }}
                        >
                            Cancel
                        </button>
                        <button
                            type="submit"
                            disabled={isSubmitting}
                            style={{
                                padding: '10px 24px', borderRadius: 8, border: 'none', backgroundColor: '#1E3A5F',
                                color: '#FFFFFF', fontSize: 14, fontWeight: 500, cursor: 'pointer',
                                display: 'flex', alignItems: 'center', gap: 8,
                                opacity: isSubmitting ? 0.7 : 1
                            }}
                        >
                            {isSubmitting ? (
                                <>Creating Fund...</>
                            ) : (
                                <>
                                    <Save size={16} /> Create Fund
                                </>
                            )}
                        </button>
                    </div>

                </form>
            </div>
        </div>
    );
}
