<!DOCTYPE html>
<html>
<head>
    <title>Payoff Letter</title>
    <style>
        body { font-family: sans-serif; }
        .header { text-align: center; margin-bottom: 30px; }
        .content { margin-bottom: 20px; }
        .details { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .details td { padding: 5px; border-bottom: 1px solid #ddd; }
        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #777; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Payoff Statement</h1>
        <p>Date: {{ now()->format('F d, Y') }}</p>
    </div>

    <div class="content">
        <p>To Whom It May Concern,</p>
        <p>This letter serves as a formal payoff statement for the property listed below. The total amount required to satisfy the lien is as follows:</p>
    </div>

    <table class="details">
        <tr>
            <td><strong>Property Address:</strong></td>
            <td>{{ $property->address }}, {{ $property->city }}, {{ $property->state }} {{ $property->zip_code }}</td>
        </tr>
        <tr>
            <td><strong>Parcel ID:</strong></td>
            <td>{{ $property->parcel_id }}</td>
        </tr>
        <tr>
            <td><strong>Owner of Record:</strong></td>
            <td>{{ $property->owner ?? 'Unknown' }}</td>
        </tr>
        <tr>
            <td><strong>Redemption Deadline:</strong></td>
            <td>{{ optional($property->redemptionTracking)->redemption_deadline ? \Carbon\Carbon::parse($property->redemptionTracking->redemption_deadline)->format('F d, Y') : 'N/A' }}</td>
        </tr>
        <tr>
            <td><strong>Principal Amount:</strong></td>
            <td>${{ number_format($property->purchase_price, 2) }}</td>
        </tr>
        <tr>
            <td><strong>Accrued Interest:</strong></td>
            <td>${{ number_format($property->interestCalculations->sum('calculated_amount'), 2) }}</td>
        </tr>
        <tr>
            <td><strong>Total Payoff Amount:</strong></td>
            <td><strong>${{ number_format((optional($property->redemptionTracking)->redemption_amount > 0 ? $property->redemptionTracking->redemption_amount : (($property->purchase_price ?? 0) + $property->interestCalculations->sum('calculated_amount'))), 2) }}</strong></td>
        </tr>
    </table>

    <div class="content">
        <p>Please remit payment via wire transfer or certified check to PCIG Fund.</p>
        <p>This payoff quote is valid through {{ now()->endOfMonth()->format('F d, Y') }}.</p>
    </div>

    <div class="footer">
        <p>Generated by PCIG System</p>
    </div>
</body>
</html>
